# Generated by Django 2.2.3 on 2019-08-12 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('college', models.CharField(max_length=256, null=True)),
                ('account_number', models.CharField(max_length=64, null=True)),
                ('billing_period', models.DateField(null=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('resource_type', models.CharField(choices=[('E', 'Electric'), ('G', 'Gas'), ('S', 'Steam')], default='E', max_length=1)),
                ('energy_usage', models.IntegerField(null=True)),
                ('demand_usage', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('meter_number', models.CharField(max_length=64, null=True)),
                ('energy_usage', models.IntegerField(null=True)),
                ('demand_usage', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_date', models.DateField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('account_file', models.FileField(upload_to='uploads/accounts/')),
                ('account_file_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('account_file_crawled', models.BooleanField(default=False)),
                ('account_crawl_result', models.IntegerField(default=0)),
                ('account_crawl_msg', models.CharField(max_length=128)),
                ('meter_file', models.FileField(upload_to='uploads/meters/')),
                ('meter_file_progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('meter_file_crawled', models.BooleanField(default=False)),
                ('meter_crawl_result', models.IntegerField(default=0)),
                ('meter_crawl_msg', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RowIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Account')),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Meter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Report')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Report'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('square_footage', models.IntegerField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Meter')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ec3exceldump.Report'),
        ),
    ]
