# Generated by Django 2.2.3 on 2019-08-12 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec3exceldump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='testing',
            field=models.CharField(default='DJANGO', max_length=32, validators=[django.core.validators.RegexValidator('A', 'Your string should contain letter A in it.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='energy_usage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
