# Generated by Django 2.2.3 on 2019-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec3exceldump', '0002_auto_20190812_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='energy_usage',
            field=models.IntegerField(null=True),
        ),
    ]
