# Generated by Django 2.2.3 on 2019-08-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec3exceldump', '0003_auto_20190812_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='testing',
        ),
        migrations.AlterField(
            model_name='report',
            name='account_file_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='meter_file_progress',
            field=models.IntegerField(default=0),
        ),
    ]
